<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Eventos;

/**
 * EventosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventosRepository extends \Doctrine\ORM\EntityRepository
{
   
    /**
     * To get events
     * 
     * @return type
     */
    public function getEvents()
    {
        $qb = $this->createQueryBuilder('e')
            ->select('e.id, e.title, e.description, e.color, e.textColor, e.start, e.end')
            ->getQuery();
        
        $events = $qb->execute();
        
        $eventos = [];
        foreach($events as $evento){
            $evento['start'] = json_encode($evento['start']);
            $start_ini = explode('"', $evento['start']);
            $start = explode('.', $start_ini[3]);
            $evento['start'] = $start[0];

            $evento['end'] = json_encode($evento['end']);           
            $end_ini = explode('"', $evento['end']);
            $end = explode('.', $end_ini[3]);
            $evento['end'] = $end[0];

            $eventos[] = $evento;
        }

        return $eventos;
    }

}
